.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. zuzcoin_qt test_zuzcoin_qt
clean: FORCE
	$(MAKE) -C .. zuzcoin_qt_clean test_zuzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_zuzcoin_qt_check
zuzcoin-qt zuzcoin-qt.exe: FORCE
	 $(MAKE) -C .. zuzcoin_qt
